# Generated by Django 4.2.5 on 2024-06-16 06:24

import apps.accounts.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.accounts.fields.TitleCharField(max_length=64, unique=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, unique=True)),
            ],
        ),
    ]
