# Generated by Django 4.2.5 on 2024-06-16 06:24

import apps.accounts.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsections', '0001_initial'),
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
        ('legends', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', apps.accounts.fields.TitleCharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booksImages/')),
                ('book', models.FileField(blank=True, null=True, upload_to='books')),
                ('notes', models.TextField(blank=True, null=True)),
                ('publisher', apps.accounts.fields.TitleCharField(max_length=128)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='authors.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='categories.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='cities.city')),
                ('legend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='legends.legend')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='subsections.subsection')),
            ],
        ),
    ]
