# Generated by Django 4.2.5 on 2024-06-16 06:24

import apps.accounts.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.accounts.fields.TitleCharField(max_length=128, unique=True)),
                ('legend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsections', to='legends.legend')),
            ],
        ),
    ]
